# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('idperformance', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('actors', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idplace', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('category_pl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_sales',
            fields=[
                ('idticket_sales', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('binocular', models.BooleanField()),
                ('row', models.IntegerField()),
                ('sit', models.IntegerField()),
                ('idperformance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_theater.Performance')),
                ('idplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_theater.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('idvisitor', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('category_vis', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ticket_sales',
            name='idvisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_theater.Visitor'),
        ),
    ]
